lend:
  price: 100
  count: 57

prize:
  large-item: GOLD_INGOT
  large-price: 1000
  medium-item: IRON_INGOT
  medium-price: 400
  small-item: IRON_NUGGET
  small-price: 100
  custom-prizes:
    - name: special diamond
      lore: |- 
        super special diamond!!
        you can get this only from slot machine!!
      item: DIAMOND
      count: 1
      price: 10000