name: SlotMachine
authors:
  - ikafly144
version: '${version}'
description: SlotMachine plugin for Minecraft
website: "https://github.com/ikafly144/SlotMachine"
main: net.sabafly.slotmachine.v2.SlotMachine
api-version: '1.21'
load: STARTUP
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    maps:
      load: BEFORE
      required: true
    floodgate:
      load: BEFORE
      required: false